---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: helm-chart
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://juan-bolivar.github.io/onboarding-tasks-pipeline

