---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-chart
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: helm-chart
  interval: 3m0s
  targetNamespace: default

