- hosts: localhost
  collections:
    - devsec.hardening
  roles:
    - {role: geerlingguy.docker , become: yes , become_user: root}
    - {role: os_hardening , become: yes , become_user: root}
  vars:
    sysctl_overwrite:
      # Enable IPv4 traffic forwarding.
      net.ipv4.ip_forward: 1
    #kubernetes_allow_pods_on_master: true
    #kubernetes_role: "node"
    
  tasks:
    - name: Add kubernetes repo keys
      ansible.builtin.shell:
        cmd: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
      become: yes
      become_user: root
    - name: Add source repository into sources list
      ansible.builtin.apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
      become: yes
      become_user: root
    - name: install aws-iam-authenticator
      ansible.builtin.shell:
        cmd: curl -o aws-iam-authenticator https://s3.us-west-2.amazonaws.com/amazon-eks/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator && chmod +x ./aws-iam-authenticator && mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin 
      become: yes
      become_user: root


      

